name = "Tensors"
uuid = "48a634ad-e948-5137-8d70-aa71f2a747f4"
version = "0.8.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
